export const IMAGE_DATA_ARRAY = [
  {url: require('../assets/dummyAssets/imageOne.jpeg')},
  {url: require('../assets/dummyAssets/imageTwo.jpg')},
  {url: require('../assets/dummyAssets/imageThree.jpg')},
  {url: require('../assets/dummyAssets/imageFour.jpg')},
  {url: require('../assets/dummyAssets/imageFive.jpg')},
  {url: require('../assets/dummyAssets/imageSix.jpg')},
  {url: require('../assets/dummyAssets/imageSeven.jpg')},
  {url: require('../assets/dummyAssets/imageEight.jpg')},
  {url: require('../assets/dummyAssets/imageNine.jpg')},
  {url: require('../assets/dummyAssets/imageTen.jpg')},
  {url: require('../assets/dummyAssets/imageEleven.jpg')},
  {url: require('../assets/dummyAssets/imageTwelve.jpg')},

  {url: require('../assets/dummyAssets/imageOne.jpeg')},
  {url: require('../assets/dummyAssets/imageTwo.jpg')},
  {url: require('../assets/dummyAssets/imageThree.jpg')},
  {url: require('../assets/dummyAssets/imageFour.jpg')},
  {url: require('../assets/dummyAssets/imageFive.jpg')},
  {url: require('../assets/dummyAssets/imageSix.jpg')},
  {url: require('../assets/dummyAssets/imageSeven.jpg')},
  {url: require('../assets/dummyAssets/imageEight.jpg')},
  {url: require('../assets/dummyAssets/imageNine.jpg')},
  {url: require('../assets/dummyAssets/imageTen.jpg')},
  {url: require('../assets/dummyAssets/imageEleven.jpg')},
  {url: require('../assets/dummyAssets/imageTwelve.jpg')},
];

export const VIRTUAL_CARDS = [
  {
    url: require('../assets/dummyAssets/disposable-virtual-card.png'),
    title: 'Disposable Virtual Card',
  },
];

export const PHYSICAL_CARDS = [
  {
    url: require('../assets/dummyAssets/natwest-card.png'),
    title: 'Original ***4509',
  },
  {
    url: require('../assets/dummyAssets/santander-card.png'),
    title: 'Original ***7452',
  },
];

export const PROFILE_DATA = {
  url: require('../assets/images/profile/profile-background.png'),
  title: 'Meditation to rel...',
  time: '4 hrs ago',
  profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
  name: 'friendsofthearth',
  post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  category: 'people',
  getInvolved: false,
  isVerified: false,
  id: '1',
  date: '05.05.21',
  interest: 'Zero Hunger',
  name: 'nora.osborn',
  followers: '5k',
  about: 'She/Her. Passionate about plants.',
  location: 'London',
  fullName: 'Nora Osborn',
  locationMap: require('../assets/dummyAssets/location.png'),
  progressBar: require('../assets/dummyAssets/progress-bar.png'),
};

export const PROFESSIONAL_PROFILE_DATA = {
  url: require('../assets/dummyAssets/pro-background.png'),
  title: 'Meditation to rel...',
  time: '4 hrs ago',
  profileImageUrl: require('../assets/dummyAssets/pro-avatar.png'),
  name: 'Friendsoftheearth',
  post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  category: 'people',
  getInvolved: false,
  isVerified: true,
  id: '1',
  date: '05.05.21',
  interest: 'Zero Hunger',
  name: 'nora.osborn',
  followers: '5k',
  about: 'Friends of the Earth Manchester',
  location: 'London',
  fullName: 'Nora Osborn',
  locationMap: require('../assets/dummyAssets/location.png'),
  progressBar: require('../assets/dummyAssets/progress-bar.png'),
};

export const PROFILE_DATA_ONE = [
  {
    url: require('../assets/dummyAssets/search7.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'people',
    getInvolved: false,
    isVerified: false,
    id: '1',
    date: '05.05.21',
    interest: 'Zero Hunger',
    name: 'sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search12.jpg'),
    title: 'Cycle for mental...',
    time: '1 day ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'planet',
    getInvolved: true,
    isVerified: true,
    id: '2',
    date: '05.05.21',
    interest: 'Zero Hunger',
    name: 'sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search11.jpg'),
    title: 'Manchester marat...',
    time: '24 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'people',
    getInvolved: false,
    isVerified: false,
    id: '3',
    date: '05.05.21',
    interest: 'Zero Hunger',
    name: 'sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search8.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'planet',
    getInvolved: true,
    isVerified: true,
    id: '4',
    date: '05.05.21',
    interest: 'Zero Hunger',
    name: 'sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search9.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'people',
    getInvolved: false,
    isVerified: false,
    id: '5',
    date: '05.05.21',
    interest: 'Zero Hunger',
    name: 'sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
];

export const PROFILE_DATA_TWO = [
  {
    url: require('../assets/dummyAssets/search1.jpg'),
    title: 'Self Care Day',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'planet',
    getInvolved: true,
    isVerified: true,
    id: '6',
    date: '05.05.21',
    interest: 'Zero Hunger',
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/dummyAssets/search2.jpg'),
    title: 'Enjoy the great out...',
    time: '1 day ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'people',
    getInvolved: false,
    isVerified: false,
    id: '7',
    date: '05.05.21',
    interest: 'Zero Hunger',
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/dummyAssets/search3.jpg'),
    title: 'Girl Power',
    time: '24 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'planet',
    getInvolved: true,
    isVerified: true,
    id: '0',
    date: '05.05.21',
    interest: 'Zero Hunger',
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/dummyAssets/search8.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'people',
    getInvolved: false,
    isVerified: false,
    id: '0',
    date: '05.05.21',
    interest: 'Zero Hunger',
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/dummyAssets/search9.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'planet',
    getInvolved: true,
    isVerified: true,
    id: '8',
    date: '05.05.21',
    interest: 'Zero Hunger',
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/dummyAssets/search7.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    category: 'people',
    getInvolved: false,
    isVerified: false,
    id: '1',
    date: '05.05.21',
    interest: 'Zero Hunger',
    name: 'sarah_wills',
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
];

export const SEARCH_PAGE_DATA = [
  {
    title: 'peopleproject',
    total: 208,
    images: PROFILE_DATA_ONE,
  },
  {
    title: 'selflove',
    total: 256,
    images: PROFILE_DATA_TWO,
  },
  {
    title: 'communitysupport',
    total: 799,
    images: [
      {
        url: require('../assets/dummyAssets/search10.jpg'),
        title: 'Community Supp...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'people',
        getInvolved: false,
        isVerified: false,
        id: '9',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search6.jpg'),
        title: 'Technology Heroes...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'planet',
        getInvolved: true,
        isVerified: true,
        id: '10',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search5.jpg'),
        title: 'Be Kind to those...',
        time: '24 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'people',
        getInvolved: false,
        isVerified: false,
        id: '11',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'planet',
        getInvolved: true,
        isVerified: true,
        id: '12',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'people',
        getInvolved: false,
        isVerified: false,
        id: '13',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'healthylifestyle',
    total: 256,
    images: [
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Sustainable Cloth...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'people',
        getInvolved: true,
        isVerified: true,
        id: '14',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search4.jpg'),
        title: 'Smoothie Week...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'people',
        getInvolved: false,
        isVerified: false,
        id: '15',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Health Check In',
        time: '24 hrs ago',

        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'planet',
        getInvolved: true,
        isVerified: true,
        id: '16',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'people',
        getInvolved: false,
        isVerified: false,
        id: '17',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        category: 'planet',
        getInvolved: true,
        isVerified: true,
        id: '18',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
];

export const HOME_SCREEN_DATA = [
  {
    url: require('../assets/images/home/home-exp-ten-background.png'),
    title: 'Live Outside',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'wunder',
    isVerified: true,
    post: 'Make sure you are getting out and about as much as possible m',
    category: 'planet',
    getInvolved: false,
    donateAction: true,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-two-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'greatormondst',
    isVerified: true,
    title: 'The difference we make, together',
    post: 'Helps us to transform the lives of seriously ill children. Every d',
    category: false,
    getInvolved: false,
    donateAction: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-three-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    isVerified: false,
    title: 'Pembury Children’s Community',
    post: 'The Pembury Children’s Community is a partnership led by the Co',
    category: 'planet',
    getInvolved: true,
    donateAction: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-four-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    isVerified: true,
    title: 'Community Food Connection Scheme',
    post: 'We’re working with FareShare, a leading food redistribution c',
    category: 'planet',
    getInvolved: true,
    donateAction: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-five-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'sam_williams',
    isVerified: false,
    title: 'Morning Central Park Run',
    post: 'Every Wednesday me and the group go for a morning run through',
    category: 'planet',
    getInvolved: false,
    donateAction: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-six-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'millissaharris10',
    isVerified: false,
    title: 'Cooking for the homeless in my n...',
    post: 'Today I will be cooking the homeless people in my area in an att',
    category: false,
    getInvolved: false,
    donateAction: false,
    navigateActions: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-seven-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'nora_osborn',
    isVerified: false,
    title: 'Self care day',
    post: 'Self care day with this new charcoal mask I received this morning',
    category: false,
    getInvolved: false,
    donateAction: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-eight-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'nora_osborn',
    isVerified: false,
    title: 'Working On Body Positivity',
    post: 'Working on myself and helping others with body positivity',
    category: false,
    getInvolved: false,
    donateAction: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-nine-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'vic_azerrenca',
    isVerified: false,
    title: 'Peaceful Walk this Morning',
    post: 'The Pembury Children’s Community is a partnership led by the Co',
    category: POST_DATA,
    getInvolved: false,
    donateAction: false,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    url: require('../assets/images/home/home-exp-one-background.png'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'wunder',
    isVerified: true,
    title: 'Healthy Eating',
    post: 'It’s recommended that you eat at least 5 portions of a variety',
    category: 'planet',
    getInvolved: false,
    donateAction: true,
    followers: '5k',
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
];

export const POST_DATA = [
  ...PROFILE_DATA_ONE,
  ...PROFILE_DATA_TWO,
  ...PROFILE_DATA_TWO,
];

export const PROJECTS_DATA = [
  {
    url: require('../assets/dummyAssets/project1.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    category: 'planet',
  },
  {
    url: require('../assets/dummyAssets/project2.jpg'),
    title: 'Adapting a pengu..',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project3.jpg'),
    title: 'Houseplants prod...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project4.jpg'),
    title: 'Save the Rainfo...',
    time: '4 hrs ago',
    coins: '90',
    date: '29/04/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project5.jpg'),
    title: 'Treeplanting to co...',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project6.jpg'),
    title: 'Adapt a turtle...',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project7.jpg'),
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project8.jpg'),
    title: 'Houseplants prod...',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project9.jpg'),
    title: 'WWF planet aware...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project10.jpg'),
    title: 'Save the sloths to...',
    time: '4 hrs ago',
    coins: '90',
    date: '29/04/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project11.jpg'),
    title: 'Cleaning Sust...',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project12.jpg'),
    title: 'Growing home gro...',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project1.jpg'),
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project2.jpg'),
    title: 'Adapting a penguin..',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project3.jpg'),
    title: 'Houseplants produc...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project12.jpg'),
    title: 'Growing home gro...',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project1.jpg'),
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project2.jpg'),
    title: 'Adapting a penguin..',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project3.jpg'),
    title: 'Houseplants produc...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    category: 'planet',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/project2.jpg'),
    title: 'Adapting a penguin..',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    category: 'people',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    post: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getInvolved: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
];

export const newPostItemArray = [
  {
    title: 'Tag People',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Location',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'People',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Planet',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Save for later?',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Advanced Settings',
    showRightIcon: true,
    showLeftIcon: false,
  },
];

export const NOTIFICATION_DATA = [
  {
    multiple: true,
    name: 'Joe Gardner & 10 others',
    createdAt: '1d',
    notificationBody: 'Applauded your post: Daily meditation for...',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'applaud',
  },
  {
    name: 'Yvonne Chin',
    createdAt: '1d',
    notificationBody: 'Applauded your post: Morning Beach Clean...',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'applaud',
  },
  {
    name: 'Susanna Fontè',
    createdAt: '2d',
    notificationBody: 'Started following you!',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'following',
  },
  {
    name: 'Susanna Fontè',
    createdAt: '2d',
    notificationBody: 'Started following you!',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'following',
  },
  {
    multiple: true,
    name: 'savetheoceans',
    createdAt: '1d',
    notificationBody: 'Applauded your post: Daily meditation for...',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'QRCode',
  },
  {
    name: 'Matt Williams',
    createdAt: '3d',
    notificationBody: 'Donated 10 coins to: Daily meditation for...',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'donate',
    coins: '10',
  },
  {
    name: 'Fiona Piscek',
    createdAt: '1w',
    notificationBody: 'Started following you!',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'follow',
  },
  {
    multiple: true,
    name: 'helptodonate',
    createdAt: '1d',
    notificationBody: 'Applauded your post: Daily meditation for...',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'QRCode',
  },
  {
    multiple: true,
    name: 'savetheplanet',
    createdAt: '1d',
    notificationBody: 'Applauded your post: Daily meditation for...',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'QRCode',
  },
  {
    name: 'Kim Smith',
    createdAt: '1w',
    notificationBody: 'Commented on your post: Wow!',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'comment',
  },
  {
    name: 'Joseph Gonzalez',
    createdAt: '1w',
    notificationBody: 'Applauded your post: Treeplanting with the...',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    url: require('../assets/dummyAssets/search2.jpg'),
    action: 'donate',
    coins: '10',
  },
];
