export const IMAGE_DATA_ARRAY = [
  {url: require('../assets/dummyAssets/imageOne.jpeg')},
  {url: require('../assets/dummyAssets/imageTwo.jpg')},
  {url: require('../assets/dummyAssets/imageThree.jpg')},
  {url: require('../assets/dummyAssets/imageFour.jpg')},
  {url: require('../assets/dummyAssets/imageFive.jpg')},
  {url: require('../assets/dummyAssets/imageSix.jpg')},
  {url: require('../assets/dummyAssets/imageSeven.jpg')},
  {url: require('../assets/dummyAssets/imageEight.jpg')},
  {url: require('../assets/dummyAssets/imageNine.jpg')},
  {url: require('../assets/dummyAssets/imageTen.jpg')},
  {url: require('../assets/dummyAssets/imageEleven.jpg')},
  {url: require('../assets/dummyAssets/imageTwelve.jpg')},
];

export const PROFILE_DATA = {
  url: require('../assets/images/profile/profile-background.png'),
  title: 'Meditation to rel...',
  time: '4 hrs ago',
  profileImageUrl: '../assets/dummyAssets/profile-fiona.png',
  name: 'friendsofthearth',
  detail: 'Walking through the park earlier, found friendly squirrel ',
  category: 'people',
  hasButton: false,
  isVerified: false,
  id: '1',
  date: '05.05.21',
  interest: 'Zero Hunger',
  profileName: '@sarah_wills',
  followers: '5k',
  about: 'She/Her. Passionate about plants.',
};

export const PROFILE_DATA_ONE = [
  {
    url: require('../assets/dummyAssets/search7.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'people',
    hasButton: false,
    isVerified: false,
    id: '1',
    date: '05.05.21',
    interest: 'Zero Hunger',
    profileName: '@sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search12.jpg'),
    title: 'Cycle for mental...',
    time: '1 day ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'planet',
    hasButton: true,
    isVerified: true,
    id: '2',
    date: '05.05.21',
    interest: 'Zero Hunger',
    profileName: '@sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search11.jpg'),
    title: 'Manchester marat...',
    time: '24 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'people',
    hasButton: false,
    isVerified: false,
    id: '3',
    date: '05.05.21',
    interest: 'Zero Hunger',
    profileName: '@sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search8.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'planet',
    hasButton: true,
    isVerified: true,
    id: '4',
    date: '05.05.21',
    interest: 'Zero Hunger',
    profileName: '@sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
  {
    url: require('../assets/dummyAssets/search9.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'people',
    hasButton: false,
    isVerified: false,
    id: '5',
    date: '05.05.21',
    interest: 'Zero Hunger',
    profileName: '@sarah_wills',
    followers: '5k',
    about: 'She/Her. Passionate about plants.',
  },
];

export const PROFILE_DATA_TWO = [
  {
    url: require('../assets/dummyAssets/search1.jpg'),
    title: 'Self Care Day',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'planet',
    hasButton: true,
    isVerified: true,
    id: '6',
    date: '05.05.21',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/search2.jpg'),
    title: 'Enjoy the great out...',
    time: '1 day ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'people',
    hasButton: false,
    isVerified: false,
    id: '7',
    date: '05.05.21',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/search3.jpg'),
    title: 'Girl Power',
    time: '24 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'planet',
    hasButton: true,
    isVerified: true,
    id: '0',
    date: '05.05.21',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/search8.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'people',
    hasButton: false,
    isVerified: false,
    id: '0',
    date: '05.05.21',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/dummyAssets/search9.jpg'),
    title: 'Meditation to rel...',
    time: '4 hrs ago',
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsofthearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    category: 'planet',
    hasButton: true,
    isVerified: true,
    id: '8',
    date: '05.05.21',
    interest: 'Zero Hunger',
  },
];

export const SEARCH_PAGE_DATA = [
  {
    title: 'peopleproject',
    total: 208,
    images: PROFILE_DATA_ONE,
  },
  {
    title: 'selflove',
    total: 256,
    images: PROFILE_DATA_TWO,
  },
  {
    title: 'communitysupport',
    total: 799,
    images: [
      {
        url: require('../assets/dummyAssets/search10.jpg'),
        title: 'Community Supp...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '9',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search6.jpg'),
        title: 'Technology Heroes...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '10',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search5.jpg'),
        title: 'Be Kind to those...',
        time: '24 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '11',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '12',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '13',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'healthylifestyle',
    total: 256,
    images: [
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Sustainable Cloth...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: true,
        isVerified: true,
        id: '14',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search4.jpg'),
        title: 'Smoothie Week...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '15',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Health Check In',
        time: '24 hrs ago',

        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '16',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '17',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '18',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
];

export const HOME_SCREEN_DATA = [
  {
    background: require('../assets/images/home/home-exp-ten-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-wunder.png'),
    profileName: '@wunder',
    verified: true,
    title: 'Live Outside',
    post: 'Make sure you are getting out and about as much as possible m',
    postTag: 'planet',
    getInvolved: false,
    donateActions: true,
  },
  {
    background: require('../assets/images/home/home-exp-two-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-ormand.png'),
    profileName: '@greatormondst',
    verified: true,
    title: 'The difference we make, together',
    post: 'Helps us to transform the lives of seriously ill children. Every d',
    postTag: false,
    getInvolved: false,
    donateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-three-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-friends.png'),
    profileName: '@friendsoftheearth',
    verified: false,
    title: 'Pembury Children’s Community',
    post: 'The Pembury Children’s Community is a partnership led by the Co',
    postTag: 'planet',
    getInvolved: true,
    donateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-four-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-vic.png'),
    profileName: '@friendsoftheearth',
    verified: true,
    title: 'Community Food Connection Scheme',
    post: 'We’re working with FareShare, a leading food redistribution c',
    postTag: 'planet',
    getInvolved: true,
    donateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-five-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-tesco.png'),
    profileName: '@sam_williams',
    verified: false,
    title: 'Morning Central Park Run',
    post: 'Every Wednesday me and the group go for a morning run through',
    postTag: 'planet',
    getInvolved: false,
    donateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-six-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-sam.png'),
    profileName: '@millissaharris10',
    verified: false,
    title: 'Cooking for the homeless in my n...',
    post: 'Today I will be cooking the homeless people in my area in an att',
    postTag: false,
    getInvolved: false,
    donateActions: false,
    navigateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-seven-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-milli.png'),
    profileName: '@nora_osborn',
    verified: false,
    title: 'Self care day',
    post: 'Self care day with this new charcoal mask I received this morning',
    postTag: false,
    getInvolved: false,
    donateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-eight-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-nora.png'),
    profileName: '@nora_osborn',
    verified: false,
    title: 'Working On Body Positivity',
    post: 'Working on myself and helping others with body positivity',
    postTag: false,
    getInvolved: false,
    donateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-nine-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-nora.png'),
    profileName: '@vic_azerrenca',
    verified: false,
    title: 'Peaceful Walk this Morning',
    post: 'The Pembury Children’s Community is a partnership led by the Co',
    postTag: 'planet',
    getInvolved: false,
    donateActions: false,
  },
  {
    background: require('../assets/images/home/home-exp-one-background.png'),
    profileIcon: require('../assets/dummyAssets/profile-wunder.png'),
    profileName: '@wunder',
    verified: true,
    title: 'Healthy Eating',
    post: 'It’s recommended that you eat at least 5 portions of a variety',
    postTag: 'planet',
    getInvolved: false,
    donateActions: true,
  },
];
