export const searchPageData = [
  {
    title: 'peopleproject',
    total: 208,
    images: [
      {
        url: require('../assets/dummyAssets/search7.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '1',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search12.jpg'),
        title: 'Cycle for mental...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '2',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search11.jpg'),
        title: 'Manchester marat...',
        time: '24 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '3',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '4',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '5',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'selflove',
    total: 256,
    images: [
      {
        url: require('../assets/dummyAssets/search1.jpg'),
        title: 'Self Care Day',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '6',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search2.jpg'),
        title: 'Enjoy the great out...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '7',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search3.jpg'),
        title: 'Girl Power',
        time: '24 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '8',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'communitysupport',
    total: 799,
    images: [
      {
        url: require('../assets/dummyAssets/search10.jpg'),
        title: 'Community Supp...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '9',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search6.jpg'),
        title: 'Technology Heroes...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '10',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search5.jpg'),
        title: 'Be Kind to those...',
        time: '24 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '11',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '12',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '13',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'healthylifestyle',
    total: 256,
    images: [
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Sustainable Cloth...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: true,
        isVerified: true,
        id: '14',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search4.jpg'),
        title: 'Smoothie Week...',
        time: '1 day ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '15',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Health Check In',
        time: '24 hrs ago',

        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '16',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'people',
        hasButton: false,
        isVerified: false,
        id: '17',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/dummyAssets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        category: 'planet',
        hasButton: true,
        isVerified: true,
        id: '18',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
];
